"""create_Organizations

Revision ID: 2d0ca002c595
Revises: a4d21b5c89be
Create Date: 2025-09-24 10:46:19.815631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0ca002c595'
down_revision: Union[str, Sequence[str], None] = 'a4d21b5c89be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('activity_id', sa.UUID(), nullable=False))
    op.alter_column('organizations', 'building_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('organizations_activities_id_fkey'), 'organizations', type_='foreignkey')
    op.create_foreign_key(None, 'organizations', 'activities', ['activity_id'], ['id'])
    op.drop_column('organizations', 'activities_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('activities_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.create_foreign_key(op.f('organizations_activities_id_fkey'), 'organizations', 'activities', ['activities_id'], ['id'])
    op.alter_column('organizations', 'building_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('organizations', 'activity_id')
    # ### end Alembic commands ###
