"""add column name from organization

Revision ID: 45b6d912ef20
Revises: ef4d12e748de
Create Date: 2025-09-29 21:30:58.636504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b6d912ef20'
down_revision: Union[str, Sequence[str], None] = 'ef4d12e748de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
